# Generated by Django 3.1.2 on 2020-10-12 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='task_group',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_group',
        ),
        migrations.AddField(
            model_name='feedback',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.task'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.lesson'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TaskGroup',
        ),
    ]
