# Generated by Django 3.1.2 on 2020-10-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201012_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
