# Generated by Django 3.1.2 on 2020-10-12 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_task_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lesson'),
        ),
        migrations.AlterField(
            model_name='task',
            name='mark',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='options',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='question_type',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
