# Generated by Django 3.1.2 on 2020-10-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201013_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='company',
            field=models.ManyToManyField(blank=True, null=True, related_name='students', to='core.Company'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
