# Generated by Django 3.1.2 on 2020-10-14 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201014_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='core.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='company',
            field=models.ManyToManyField(blank=True, related_name='students', to='core.Company'),
        ),
    ]
