# Generated by Django 3.1.2 on 2020-10-14 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201014_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='core.module'),
        ),
    ]
