# Generated by Django 3.1.2 on 2020-10-14 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20201014_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='lesson',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.lesson'),
        ),
    ]
