# Generated by Django 3.1.2 on 2020-10-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20201014_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stream',
            field=models.ManyToManyField(related_name='students', to='core.Stream'),
        ),
    ]
