# Generated by Django 3.1.2 on 2020-10-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20201015_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='mark',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
