# Generated by Django 3.1.2 on 2020-10-16 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20201016_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['number']},
        ),
        migrations.AlterField(
            model_name='solution',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='core.student'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='core.task'),
        ),
    ]
