# Generated by Django 3.1.2 on 2020-10-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20201018_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='theory',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
