# Generated by Django 3.1.2 on 2020-10-19 10:36

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_lesson_theory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='theory',
            field=tinymce.models.HTMLField(),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('1', ''), ('2', ''), ('3', '')], max_length=1, verbose_name='Тип вопроса')),
                ('question_text', models.CharField(max_length=300)),
                ('answers', models.CharField(max_length=200)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.task')),
            ],
        ),
    ]
