# Generated by Django 3.1.2 on 2020-10-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20201019_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('1', 'Radiobutton'), ('2', 'Checkbutton'), ('3', 'TextArea')], max_length=1, verbose_name='Тип вопроса'),
        ),
    ]
