# Generated by Django 3.1.2 on 2020-10-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20201024_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='picture_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
