# Generated by Django 3.1.2 on 2020-11-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20201031_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hint',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
