# Generated by Django 3.1.2 on 2020-11-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20201113_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='variant',
            field=models.ManyToManyField(to='core.Variant'),
        ),
        migrations.AddField(
            model_name='variant',
            name='mark',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='solution',
            name='text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
