# Generated by Django 3.1.2 on 2020-11-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20201113_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choice',
        ),
        migrations.AddField(
            model_name='question',
            name='mark',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='solution',
            name='variant',
            field=models.ManyToManyField(related_name='solutions', to='core.Variant'),
        ),
    ]
