# Generated by Django 3.1.2 on 2020-11-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20201114_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='question_type',
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(blank=True, choices=[('1', 'Radiobutton'), ('2', 'Checkbutton'), ('3', 'TextArea')], max_length=1, null=True),
        ),
    ]
