# Generated by Django 3.1.2 on 2020-11-18 07:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0034_auto_20201116_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='author',
            field=models.ManyToManyField(related_name='modules', to=settings.AUTH_USER_MODEL),
        ),
    ]
