# Generated by Django 3.1.2 on 2020-11-18 10:16

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0035_module_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewStudent',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('company', models.ManyToManyField(blank=True, related_name='newstudent', to='core.Company')),
                ('stream', models.ManyToManyField(blank=True, related_name='newstudents', to='core.Stream')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
