# Generated by Django 3.1.2 on 2020-11-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_newstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='seen',
            field=models.BooleanField(default=False, verbose_name='Просмотрено'),
        ),
    ]
