# Generated by Django 3.1.2 on 2020-11-19 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_feedback_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='question',
            name='slug',
        ),
    ]
