# Generated by Django 3.1.2 on 2020-12-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20201206_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.FileField(default=1, upload_to='mio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='type',
            field=models.CharField(default='jpg', max_length=10),
            preserve_default=False,
        ),
    ]
