# Generated by Django 3.1.2 on 2020-12-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20201208_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('1', 'Radiobutton'), ('2', 'Checkbutton'), ('3', 'TextArea'), ('4', 'OneCheckbox')], max_length=1, verbose_name='Тип вопроса'),
        ),
    ]
