# Generated by Django 3.1.2 on 2020-12-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20201209_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='hint',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(blank=True, choices=[('1', 'Radiobutton'), ('2', 'Checkbutton'), ('3', 'TextArea'), ('4', 'OneCheckbox')], max_length=1, null=True),
        ),
    ]
